# This pipeline is designed to foster sharing our text mate grammars.

resources: 
  repositories:
    - repository: self
      clean: true
    - repository: VS-Platform
      type: git
      name: DevDiv/VS-Platform

trigger: none
pr: none

pool: 
  name: "AzurePipelines-EO"
  demands:
    - ImageOverride -equals AzurePipelinesWindows2022compliant

name: $(Date:yyMMdd)$(Rev:rrr)

steps:
  - checkout: self
  - checkout: VS-Platform
  - task: PowerShell@2
    inputs: 
      targetType: inline
      script: |
        Write-Output "${{variables.targetPath}}"
        Write-Output "$env:TARGETPATH"
        Write-Output "$env:BUILD_BUILDNUMBER"
        Copy-Item $(Build.SourcesDirectory)/vscode-cmake-tools/syntaxes/* $(Build.SourcesDirectory)/VS-Platform/$env:TARGETPATH
        $differences = git diff --exit-code
        Write-Output "$differences"
        if ( $differences )
        {
            git checkout -b updatingCMakeTextmates/$env:BUILD_BUILDNUMBER
            git config --global user.email '$env:EMAIL'
            git config --global user.name '$env:USERNAME'
            git add *; git commit -m "updating textmate"
            git push --set-upstream origin updatingCMakeTextmates/$env:BUILD_BUILDNUMBER
            $env:AZURE_DEVOPS_EXT_PAT = $env:SYSTEM_ACCESSTOKEN
            az repos pr create --draft true --title "[Textmate AutoPR] $env:BUILD_BUILDNUMBER" --org $env:ORGURL -p DevDiv
        }
        else
        {
            Write-Output "no differences"
        }
      workingDirectory: $(Build.SourcesDirectory)/VS-Platform

  