# This pipeline is designed to foster sharing our text mate grammars.

resources: 
  repositories:
    - repository: self
      clean: true
    - repository: VS-Platform
      type: git
      name: DevDiv/VS-Platform

trigger: none
pr: none

pool: 
  name: "AzurePipelines-EO"
  demands:
    - ImageOverride -equals AzurePipelinesWindows2022compliant

variables:
  date: $(Date:yyMMdd)$(Rev:rrr)

steps:
  - checkout: self
  - checkout: VS-Platform
  - task: PowerShell@2
    inputs: 
      targetType: inline
      script: |
        Write-Output "${{variables.targetPath}}"
        Copy-Item $(Build.SourcesDirectory)/vscode-cmake-tools/syntaxes/* $(Build.SourcesDirectory)/VS-Platform/src/Productivity/TextMate/VSWindows/Setup/Starterkit/Extensions/cmake/Syntaxes
        $differences = git diff --exit-code
        Write-Output "$differences"
        if ( $differences )
        {
            git checkout -b updatingCMakeTextmates/${{variables.date}}
            git add *; git commit -m "updating textmate"
            git push --set-upstream origin updatingCMakeTextmates/${{variables.date}}
            $env:AZURE_DEVOPS_EXT_PAT = $(System.AccessToken)
            az repos pr create --draft true --title "[Textmate AutoPR] ${{variables.date}}" --org $(orgUrl) -p DevDiv
        }
        else
        {
            Write-Output "no differences"
        }
      workingDirectory: $(Build.SourcesDirectory)/VS-Platform

  